# Satzungsvorlage für eine Wähler:innenvereinigung
Benjamin Kampmann <ben@gnunicorn.org>, [Radikal*](https://radikal.jetzt)
v0.9, 14.02.2020
:sectanchors:
:lang: de
:toc:
:pagelayout: docs

## Einleitung

### Vorwort

Dies ist die Vorlage für eine moderne, progressive Wähler:innenvereinigung auf Komunaler Ebene. Diese verfügt über einige Besonderheit, einige davon können im nachhinhein nicht mehr so einfach eingefügt werden. So ist diese Organisation

🌐 Online-first:: Alle Gremien, inklusive des Plenum, tagen dauerhaft und sind damit jederzeit beschlussfähig, was durch den Einsatz von Online Tools (wir empfehlen Loomio) ermöglicht. das Plenum kommt nur zu Personenwahlen zusammen, alle Beschlüsse laufen über das Onine-Verfahren. 
📝 Flexibel:: Die Antrags- und Beschlussshöhen sind absichtlich niedrig angesetzt, nur wenige Paragraphen genießen einen zusätzlichen Schutz durch eine höher Hürde als einen einfachen Mehrheitbeschluss. Dadurch kann die Satzung auch einfach iterativ der praktischen Arbeit angepast werden. Insbesonder auch darüber, ob sich diese Organistion anderen Organisationen anschließt.
🤳 Anti-Ego:: Neben der klar formulierten Erwartungshaltung eines wertschätzenden Umgangs miteinander, sieht die Satzung auch einen Verhaltenskodex, Moderation, Rednerinnenlisten und Revisions-Gremien (Schiedsgericht) vor um Konflikte zu vermeinden und einen inklusiven Umgang der vielen Stimmen raum gibt, zu gestalten. Mandatsträger:innen sind zur Transparenz über die Einnahmen und Zurückspielen von Geldern selbstverpflichtet.
🚀 Kollaborativ und Arbeitsorient:: ADie Aufgaben des Vorstands werden hier von einem Koordinierungsauschuss übernommen, die meiste inhaltliche und thematische Arbeit durch Arbeitsgruppen, die auch das Plenum selbst einberufen kann. Für alle Wahlen sind bereits Blockwahlen vorgesehen, damit sich hier gleich ganze Teams, die gut miteinander arbeiten können, zur Wahl stelllen können.
🌈 Progressiv quotiert:: Gleichzeitig erkennt die Satzung die strukturelle Benachteiligung bestimmter Gruppen an und verfügt über ein progressives Modell mit der sich die Vereinigung zwingt dagegen auch strukturell vorzugehen, Benachteiligte und ihren Nachwuchs fördert und politische Stimme verleiht.
🔐 DSGVO konform:: Als über ein Online Verfahren Abstimmende Organisation steht die Frage des Datenschutz auch mit auf dem Programm und wird von beginn an in der Satzung geklärt.
🤝 mit politischen Konsens:: Um von vorneherein bestimmte Grabenkämpfe nicht zu führen und den Problemen aus dem Weg zu gehen, kommt die Satzung mit einem politischen Konsens (den wir empfehlen anzupassen!) und bestimmten Ausschlusskriterien der Mitgliedschaft.
⛓ und dezentraler Mitgliederstruktur:: Das innovative Mitgliederstruktur-Modell dieser Vereinigung erlaubt es auch anderen Vereinen oder Parteien der Organisation beizutreten, wodurch deren Mitgieder automatisch auch Stimm- und Wahlberechtigte werden. Das erlaubt auf bestehende Strukturen aufzusetzen und eine Mitgliederinnen-Liste zu führen, die ansich dezentral gestaltet ist –- was wiederum die hemmschwelle der Beteiligung senkt und gleichzeitig die Einzellperson schützt.


### Disclaimer
[WARNING]
====
Auch wenn diese Vorlage weitesgehend aus bestehenden sich im Einsatz befindenden Dokumenten zusammengestellt ist (siehe die Quellen), so kann für den Inhalt keine Gewähr oder Rechtssicherheit gegeben werden.
====


### ToDo's, Feedback & Support

* [x] übernommene Version überarbeiten
** [x] format anpassen
** [x] namen anpassbar machen
* [x] Klimakonsens festschreiben
* [x] Vielfaltsförderung festschreiben
* [x] Blockwahlverfahren beschreiben, Quoten festlegen
* [x] Online Befragungen und Abstimmungen festlegen
* [x] Konkretiesierung der "Demokratie" für Arbeitskreise
* [x] Konkretesierung von Projekt- und dauerhaften Arbeitsgruppen
* [x] Umwandlung und Auflösung
* [x] Vorwort
* [x] verschwörungstheorien
* [x] Instituitionellle Mitglieder benennen, nur deren Annahme vom Plenum bestätigen lassen
* [x] Vollversammlung -> Plenum
* [ ] Datenschutz bei Online-Teilnahme
* [x] Einzellmitglieder bei Abstimmungen und Wahlen
* [ ] Quorum für Anträge

### Quellen
- [1] <https://linke-liste-nürnberg.de/satzung-der-linken-liste-nuernberg/>
- [2] <https://bewegung.jetzt/partei/satzung/>
- [3] <https://bewegung.jetzt/ethik-kodex/?
- [4] <https://liquidlabs.org/satzung>

---

<<<

# Satzung

:sectnums:
## Name, Sitz
. Die Vereinigung führt den Namen „{{Name}}“
/// hier den Namen der Vereinigung eintragen
. Die Vereinigung ist eine Wählervereinigung gemäß Paragraph Art. 24 . Satz 3 GLKrWG und ein nicht eingetragener Verein gemäß BGB. Die Vereinigung kann aufgrund eines Beschlusses des Plenums in das Vereinsregister eingetragen werden.
. Die Vereinigung ist begrenzt auf das Einzugsgebiet {{Ort}}.
. Die Vereinigung hat Ihren Sitz in {{Ort}}.

## Ziel und Zweck
. Die Vereinigung ist eine Wählervereinigung und politische Vereinigung.
. Zweck der Vereinignung ist die Mitwirkung am politischen Willensbildungsprozess und die Teilnahme an den kommunalen Wahlen.
. Der Satzungszweck wird verwirklicht durch
   * die Durchführung des Plenums, von Arbeitsgruppen,politischen Veranstaltungen und öffentlichen Aktionen
   * die Abgabe von politischen Erklärungen und Publikationen
   * Anträge und Anfragen auf kommunaler Ebene
. Die Vereinigung bekennt sich
.. zum Menschen-gemachten Klimawandel und der daraus resultierenden Klimakatastrophe. Wir erkennen an, dass dieser überproportional von den Reichen dieser Welt verursacht wurde und wird und die Ärmsten darunter am Stärksten leiden und leiden werden. Wir erkennen unsere Verantwortung an, dass Maßnahmen dazu nicht zu Lasten der bereits Benachteiligten getroffen dürfen, sondern vor allem die Verursacher zur Verantwortung gezogen werden. Wir bekennen uns zur lokalen und globalen Klimagerechtigkeit. 
.. zur Verkehrswende, Energiewende und dem Systemwandel der nötig ist um die schlimmsten Folgen der Klimakatastrophe abzuwenden.
.. zum Vorrang der fundamentalen Menschenrechte für alle Menschen, wie sie in der Allgemeinen Erklärung der Menschenrechte in der Generalversammlung der Vereinten Nationen am 10.12.1948 verkündet wurden – insbesondere des Rechts auf Gesundheit, körperliche Unversehrtheit, ein menschenwürdiges Leben, soziale Sicherheit und Asyl bei Verfolgung.
.. zum Vorrang der natürlichen Lebensgrundlagen und ihres Schutzes gegenüber damit unvereinbaren wirtschaftlichen und politischen Interessen.
.. im Sinne des Völkerverständigungsgedankens und der Menschenrechte zur Solidarität mit benachteiligten Menschen im sogennanten globalen Süden.
.. zur Sozialbindung des Eigentums, wie sie in Artikel 14 Absatz 2 des Grundgesetzes der Bundesrepublik Deutschland definiert ist.
.. zur Bewahrung, Stärkung, Durchsetzung und zum Ausbau der Rechte der Bürger:innen, dabei insbesondere von benachteiligten und diskriminierten Menschen.
.. zur Verteidigung und zum Ausbau der kommunalen Demokratie und Büger:innenbeteiligung, z.B. durch die Stärkung des kommunallen Parlaments, sowie der Verbesserung der Mitspracherechte der Beiräte und Bürger:innen, z.B. in Form von Beteiligungshaushalten und der Förderung direkter Mitwirkungsrechte (Volksbefragungen und –entscheide und Bürger:innenräte).
.. zu den kommunalpolitischen Eckpunkten. Diese sind:
* Es ist für uns selbstverständlich, gegen jede Art von Diskriminierung, gegen Rassismus, Antisemitismus und Ausländerfeindlichkeit aufzutreten. Jeder Versuch von alten und neuen Nazis in der Öffentlichkeit noch stärker Fuß zu fassen, muss deshalb zurückgewiesen werden
* Global denken, lokal handekn -- dies gilt insbesondere beim Thema Klimagerechtigkeit. Daher fordern wir den Klimanotstand auszurufen und alle bestehenden, wie auch zukunftigen politischen Entscheidungen auf ihren direkten wie auch indirekten Klimaeinfluss zu prüfen. 
* Wir legen alle Bezüge, die wir im Zusammenhang mit Mandaten erhalten, offen. Unsere Mandatsträger:innen verpflichten sich ein Drittel ihrer Aufwandsentschädigungen der Vereinigung für politische Arbeit und den Sozialfonds zur Verfügung zu stellen.
* Wir handeln entsprechend unserem Programm und nutzen unsere Mandate um gemeinsam mit Betroffenen öffentlichen Druck zu entwickeln!

## Mitgliedschaft
. Mitglieder der Vereinigung sollen sich aktiv an der Umsetzung des Vereinigungszwecks beteiligen.
. Mitglieder können werden:
.. natürliche Personen, die das vierzehnte Lebensjahr vollendet haben, Wohnort, Arbeitsstelle oder Lebensmittelpunkt im Einzugsgebiet der Vereinigung haben und Satzung und Programm anerkennen
.. Vereine (-Gliederungen) und Parteien (-Gliederungen) mit politischem Bezug zum Einzugsgebiet -- sogn. institutionelle Mitglieder.
+
Die Mitglieder dieser institutionellen Mitglieder sind automatisch Mitglied der Vereinigung, außer sie erklären gegenüber ihren Vorständen schriftlich, dass sie daran nicht teilhaben wollen. Der Verzicht auf die Mitgliedschaft bei der Vereinigung berührt den Status in ihrem jeweiligen Verein oder Partei nicht.
. Mitglied kann nicht sein, wer
.. einer Organisation angehört, deren Ziele im Widerspruch zu den Zielen der Vereinigung steht. Die Feststellung der Unvereinbarkeit trifft das Plenum mit absoluter Mehrheit.
.. einer Partei, Organisation oder Vereinigung angehört oder sich schriftlich oder öffentlich zu einer solchen bekennt, die rassistisches, faschistische, antisemitisches, verschwörungstheoretisches oder antidemokratisches Gedankengut verbreitet hat.
. Die Mitgliedschaft beginnt mit der Aufnahme durch den Koordinierungsausschuss der Vereinigung. Eine Bestätigung der Aufnahme von Institutionelllen Mitglieder erfolgt durch das Plenum.
. Die Vereinigung führt eine zentrale Mitgliederdatei der Einzelmitglieder. Diese darf nur die Daten enthalten, die für die Zwecke der Vereinigung nötig sind. Auf eine strikte Einhaltung des Bundesdatenschutzgesetzes ist zu achten. Alle Mitglieder, die über die Mitgliedschaft eine institutionelles Mitglied sind, werden über ihre Organisation erfasst und betreut.

Jedes institutionelle Mitglied benennt eine Informationsperson und eine Stellvertretung. Sie haben die Aufgabe, Informationen, Einladungen zu Wahlversammungen, Kommunalpolitischen Foren und andere Einladungen zu Veranstaltungen der Vereinigung, sowie den Zugang zu den online Beteiligungsformaten an die Mitglieder ihrer Organisation, die Mitglieder in der Vereinigug sind, weiter zu leiten.

## Beendigung der Mitgliedschaft
. Die Mitgliedschaft endet durch Austritt, Ausschluss oder Tod.
. Der Austritt aus der Vereinigung ist jederzeit zulässig. Er erfolgt durch eine schriftliche Erklärung gegenüber dem Koordinierungsausschuss.
. Ein Mitglied kann ausgeschlossen werden, wenn es vorsätzlich gegen die Satzung oder erheblich gegen die Grundsätze des Programms verstoßen oder der Vereinigung erheblichen Schaden zugefügt hat. Eine Betätigung nach 3.3 ist ein solch schädigendes Verhalten und begründet einen Ausschluss.
. Der Ausschluss kann nur als Folge eines Schiedsverfahrens erfolgen. Bei Einleitung eines Schiedsverfahrens entscheidet die Schiedskommission endgültig innerhalb eines Monats. Die Mitgliedsrechte bleiben bis zur Entscheidung der Schiedskommission bestehen.

## Grundsätze der Zusammenarbeit

. Die Mitglieder pflegen einen wertschätzenden Umgang miteinder,der das Gemeinsame und den inneren Konsens sucht. Dabei ist aufeinander, insbesondere auf die Bedürfnisse betroffener und davon benachteiligter Menschen, Rücksicht zu nehmen und einzugehen.
. Die Vereinigung hat einen Verhaltenskodex, der die Erwartungshaltung an die Mitglieder und alle Gäste bei Veranstaltungen formuliert und aktiv durchgesetzt wird.
. Die Vereinigung will jedem Mitglied, unabhängig von persönlichen Einschränkungen hinsichtlich Raum und Zeit und mögliche Einschränkungen, eine umfassende Teilnahme an der Meinungs- und Willensbildung ermöglichen. Daher treten die Organe grundsätzlich online zusammen und tagen grundsätzlich ständig.
. Die Mitglieder verwenden technische Systeme um die -- bevozugt asynchrone -- Zusammenarbeit, sowie die Meinungs- und Willensbildung zu ermöglichen. Die dafür notwendigen technischen System werden von der Vereinigung zur Verfügung gestellt. Die Daten auf diesen Systemen, und damit auch die Nutzerinnen-Daten, sind als öffentlich zu betrachten.
. Jedes Organ kann sich eine Moderation bestimmen, die Verfahrensabläufe vorschlägt, überwacht und moderierend in den Meinungs- und Willensbildungsprozess eingreifen kann.
. Ein Organ kann beschließen, ausnahmsweise zur Behandlung einzelner Sachverhalte zeitlich und räumlich zusammenzutreten.
. Ein Organ tritt zur Stimmabgabe bei geheimen Wahlen an einer oder mehreren über das Tätigkeitsgebiet der jeweiligen Gliederung verteilten Wahlurnen zusammen.
. Die Mitglieder eines Organs sind an der aktiven Mitarbeit verpflichtet, es liegt in ihrer Verantwortung an Diskussionen und der Beschlussfassung teilzunehmen. 
. Sofern das Organ keine abweichenden Regeln getroffen hat,  gelten die folgenden Abstimmungsregeln zur Beschlussfassung:
* Eine Beschlussvorlage muss mindestens 3 Werktage (72 Stunden) zur Debatte stehen, damit allen die Möglichkeit gegeben ist, daran teilzunehmen.
* Vorschläge zu Verfahrensweisen müssen mindestens 5 Werktage diskutiert und danach 5 Werktage abgestimmt werden können (also insg. mind 10 Werktage Zeit vergehen), damit alle Aspekte in Ruhe bedacht und abgewogen werden können.
* Beschlüsse können auch vorher abgeschlossen werden, sofern alle Mitglieder an der Abstimmung teilgenommen haben.
* Wenn mehr dafür als dagegen gestimmt haben, gilt ein Antrag als angenommen und nach Abschluss der Abstimmung als sofort gültig.

## Beteiligungsförderung

. Die politische Willensbildung von Frauen, jungen Menschen und Menschen mit Diskriminierungserfahrung wird aktiv gefördert. Es ist Ziel der Vereinigung, dass keine Personen diskriminiert oder in ihrer politischen Arbeit behindert werden. Frauen, junge Menschen und Menschen mit Diskriminierungserfahrung haben das Recht, innerhalb der Vereinigun eigene Strukturen aufzubauen und eigene Arbeitsgruppen einzuberufen.
. Diskriminierte Menschen sind Mensch die aufgrund von Rassismus, ihrer Behinderung, ihrer sexuellen Orientierung oder ihrer Geschlechtsidentität, auch jenseits binärer Geschlechternormen, Diskriminierungserfahrungen gemacht haben. Frauen sind Menschen, die von der Gesellschaft nicht als normative Männer betrachtet werden. Junge Menschen sind Menschen, die das 25. Lebensjahr noch nicht vollendet haben.
. In allen Versammlungen wird eine getrennte Redeliste für Frauen geführt. Unter der Voraussetzung entsprechender Wortmeldungen wird mindestens jeder zweite Redebeitrag von dieser Redeliste aufgerufen. Bei begrenzter Anzahl an Redebeiträgen, sind die jenigen zu bevorzugen, die bisher am Wenigsten auf der Veranstaltung gesagt haben.
. Niemand sollte mehr als zwei Legislaturen das selbe Amt oder Mandat inne haben. Diese Person kann ein drittes mal nur antreten, wenn es vorher einen 2/3 Beschuss des jeweilig wählenden Organs gab, dass die Zulassung genehmigt hat.
. Bei allen gewählten Organen ist auf einen Anteil von mindestens 50% Frauen, 25% diskriminierte Menschen und 15% junge Menschen hinzuwirken, wobei einzellne Personen mehrere Merkmale in sich vereinen können.
. Bei der Aufstellung von Wahllisten ist der erste Platz und dann mindestens jeder zweite Platz an eine Frau zu vergeben, der spätestens dritte und dann mindestens jede vierte Platz an einen diskriminierten Menschen und spätestens der fünfte und dann jeder vierte Platz an einen jungen Menschen zu vergeben, wobei einzellne Personen mehrere Merkmale in sich vereinen können.
. Diese Quotierungen sind auch bei Blockwahlvorschlägen einzuhalten.
. Der Paragraph zur Beteiligungsförderung kann nur mit einem 2/3-Beschluss des Plenums verändert werden.

## Organe der Vereinigung
Organe der Vereinigung sind das Plenum, die Wahversammlung, der Koordinierungsausschuss, die Schiedskommission, die Kassenrevision und die Arbeitskreise.

## Das Plenum
. Das Plenum ist die Mitgliederversammlung der Vereinigung. Sie ist das höchste Organ der Vereinignung. Sie kann Beschlüsse aller Art fassen, die die Arbeit und Ausrichtung der Vereinigung betreffen. 
. Sie tagt grundsätzlich asynchron online und dauerhaft. Sie bestimmt eine Moderation, die die Durchführung leitet.
. Sie entscheidet über die Satzung und deren Änderung. Sofern ein Absatz der Satzung keine abweichende Regelung vorsieht, genügen für alle Beschlüsse die einfache Mehrheit der abgebenen Stimmen.
. Sie beschließt über Anträge, politische Ausrichtung und Programme und führt politische Grundsatzdiskussionen.
. Sie nimmt Berichte der Mandatsträger:innen entgegen.
. Sie nimmt einen Rechenschaftsbericht über die Finanzen der Vereinigung entgegen und entscheidet über die Rechtmäßigkeit der Ausgaben.
. Sie legt die Größe und Amtszeit des Koordinierungsausschusses,der Schiedskommision, der Kassenrevision fest.
. Sie kann den Koordinierungsausschuss verpflichten eine Wahlversammlung einzuberufen.

## Die Wahlversammlung
. Die Wahlversammlung ist das räumliche Zusammenkommen der Mitgliederversammlung um Personenwahlen durchzuführen.
. Dafür wird vom Koordinierungsausschuss mit Angabe einer Tagesordnung und den zu wählenden Ämtern schriftlich im Plenum und per E-Mail einberufen. Es ist ordentlich eingeladen, wenn die Informationsverantwortlichen der institutionellen Mitglieder und die Einzelmitglieder spätestens 14 Tage vor dem Zusammenkommen den Einladungstext vom Koordinierungsausschuss bekommen haben. 
. Während der Wahlversammlung ist die ständige online Versammmlung unterbrochen. Die Wahlversammlung ist beschlussfähig, wenn zu ihr ordnungsgemäß einberufen wurde.
. Die Wahlversammlung wählt:
 - Den Koordinierungsausschuss. Dies kann auch per Blockwahl geschehen. Die Quotierungen zur Vielfalts- und Jugendförderung sind in allen Fällen einzuhalten.
 - Die Schiedskommission. Dies kann auch per Blockwahl geschehen. Die Quotierungen zur Vielfalts- und Jugendförderung sind einzuhalten, einzelllne Regelungen können vorrübergehend ausgesetzt werden, wenn diese nicht eingehalten werden können. Ein Aussetzen aller Quotierungsanforderungen ist nicht möglich.
 - Die Kassenrevision. Dies kann auch per Blockwahl geschehen.
. Die Wahlversammlung kann als Aufstellungsversammlung von Kandidat:innen fungieren, wenn die Wahl in der Einladung angekündigt worden ist. Hierbei sind nur diejenigen Mitglieder wahlberechtigt, die die Kriterien des jeweiligen Kommunalwahlgesetzes erfüllen. Auch die Aufstellungsversammlung kann die Liste per Blockwahl bestimmen.

## Der Koordinierungsausschuss
. Der Koordinierungsausschuss vertritt die Vereinigung rechtlich und nimmt alle Funktionen eines Vorstands gemäß §26 BGB wahr.
. Der Koordinierungsausschuss führt die Vereingung.
. Er bestimmt aus seiner Mitte eine:n Schatzmeister:in.
. Der Koordinierungsausschuss tagt online und dauerhaft.
. Zu seinen Aufgaben gehören u. a.:

* die Umsetzung der Beschlüsse des Plenums
* Planung und Koordination der politischen Arbeit
* die Abgabe von Erklärungen zu aktuellen politischen Fragen
* die Koordination zwischen den Arbeitskreisen.
* Veröffentlichung der jeweils gültigen Satzung und Beschlusslage.
. Der Koordinierungsausschuss kann Entscheidungen finanzieller Art nur im Rahmen der Mittel der Vereinigung oder aufgrund eines Beschlusses des Plenums treffen.
. Der Koordinierungsausschuss entscheidet über die Anerkennung von Untergliederungen und Arbeitskreisen sowie über die Zusammenarbeit mit Interessengruppen. Eine Bestätigung erfolgt durch das Plenum.
. Er kann Aufgaben auf Widerruf an Arbeitskreise oder Einzelpersonen delegieren.
. Der Koordinierungsausschuss lädt zur Aufstellungsversammlung ein. Die Einladung und der Inhalt der Aufstellungsversammlung entsprechen den Kriterien des Kommunalwahlrechts.

## Die Schiedskommission
. Die Schiedskommission besteht aus mindestens drei Mitgliedern. Die Mitglieder der Schiedskommission dürfen nicht gleichzeitig Mitglied des Koordinierungsausschusses sein.
. Die Schiedskommission tagt dauerhaft online.
. Die Schiedskommission wird nur auf Antrag des Koordinierungsausschusses, des Plenums oder eines Mitglieds, das selbst von einem Vorgang direkt und erheblich betroffen ist, tätig.
. Die Schiedskommission entscheidet mit Zweidrittelmehrheit über Verstöße gegen die Satzung.

## Arbeitskreise
. Arbeitskreise werden auf Beschluss des Plenums oder des Koordinierungsausschusses gegründet. Sie arbeiten zu einem bestimmten Thema, Arbeitsbereich oder Projekt.
. Sie geben sich selbst eine demokratische Struktur, die ihren Anforderungen entspricht, sie benennen eine Ansprechperson.
. Sie sind den Mitgliedern zugänglich. Die Mitarbeit von Einzellpersonen kann aber aufgrund von Mehrheitsbeschlüssen der anderen Mitglieder oder auf Beschlluss des Koordinierungsausschuss eingeschränkt werden.
. Die Arbeitskreise können Gäste einladen.

## Vereinigungsmittel
. Für Mitglieder von Mitgliedsvereinen und -parteien ist der Mitgliedsbeitrag mit dem satzungsgemäßen Vereins- bzw. Parteibeitrag für ihren jeweiligen Verein oder Partei abgegolten. Im Gegenzug tragen die Mitgliedsvereine und -Parteien zu den laufenden Kosten der Vereinigung bei.
. Die Höhe des Mitgliedsbeitrags für alle natürlichen Mitglieder der Vereinigung regelt eine Beitragsordnung, die das Plenum beschließt.
. Der Mitgliedsbeitrag wird zentral über den Koordinierungsausschuss erhoben.
. Zeichnungsberechtigt sind jeweils Schatzmeister:in und stellvertretende:r Schatzmeister:in. Gibt es keine:n stellvertretende:n Schatzmeister:in, bestimmt der Koordinierungsausschuss eine:n zweite:n Zeichnungsberechtigte:n aus seiner Mitte.
. Über diese Mittel hat der Koordinierungsausschuss die Finanzhoheit. Darüber hinausgehender Finanzbedarf ist anlassbezogen von den Mitgliedsvereinen und –Parteien fallweise zu beschließen.

## Schluss- und Übergangsbestimmungen
. Die Vereinigung kann aufgrund eines Beschlusses der Vollverstammlung mit einer zweidrittel Mehrheit aufgelöst werden. Für den Beschluss um mit einer anderen politischen Organisation verschmolzen oder sich als Untergliederung dieser zu erklären reicht die einfache Mehrheit des Plenums.
+
Löst sich die Vereinigung durch Verschmelzung mit einer anderen politischen Organisation auf, geht das Vermögen an diese über. In allen anderen Fällen geht das Vermögen an die Mitglieder zu gleichen Teilen (BGB §45).
. Sollte eine oder mehrere Bestimmungen dieser Satzung rechtsunwirksam sein, so berührt dies nicht die Gültigkeit der übrigen Bestimmungen. Soweit Bestimmungen in dieser Satzung unwirksam sein sollten oder die Satzung eine Regelungslücke enthalten sollte, sind die Vorschriften des BGB über den eingetragenen Verein entsprechend anzuwenden.
